[package]
name = "insert_data_into_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
postgres = "0.19.7"
quick-xml = "0.31.0"
serde = { version = "1.0", features = ["derive"] }
